[versions]
kotlin = "2.0.20"
paper = "1.12.2-R0.1-SNAPSHOT"
litecommands = "3.4.1"
shadow = "8.3.2"
menuinv = "1.5.10"
vault = "1.7"
ormlite = "6.1"
h2 = "2.3.232"
hikaricp = "4.0.3"

[libraries]
paper-api = { module = "com.destroystokyo.paper:paper-api", version.ref = "paper" }
litecommands = { module = "dev.rollczi:litecommands-bukkit", version.ref = "litecommands" }
menuinv = { module = "com.github.BoomEaro:MenuInv", version.ref = "menuinv" }
vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
ormlite = { module = "com.j256.ormlite:ormlite-jdbc", version.ref = "ormlite" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
